#!/usr/bin/env python3
"""Build single_include/brainsort.hpp from include/brainsort/.

The public header and everything it includes from the library are pasted
into one file, each library header once, in dependency order; system
includes are kept where they are. With --check the script only verifies that
the committed single header is current and exits 1 if it is not.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
INCLUDE = ROOT / "include"
ENTRY = "brainsort/brainsort.hpp"
OUT = ROOT / "single_include" / "brainsort.hpp"

INCLUDE_RE = re.compile(r'^\s*#\s*include\s+"(brainsort/[^"]+)"\s*$')
VERSION_RE = re.compile(r'#define BRAINSORT_VERSION "([^"]+)"')


def version():
    text = (INCLUDE / "brainsort/detail/config.hpp").read_text(encoding="utf-8")
    m = VERSION_RE.search(text)
    return m.group(1) if m else "unknown"


def amalgamate():
    seen = set()
    out = []

    def expand(rel):
        if rel in seen:
            return
        seen.add(rel)
        text = (INCLUDE / rel).read_text(encoding="utf-8")
        out.append(f"// ======== {rel} ========")
        for line in text.splitlines():
            m = INCLUDE_RE.match(line)
            if m:
                expand(m.group(1))
                continue
            if line.strip() == "#pragma once":
                continue
            out.append(line)
        out.append("")

    expand(ENTRY)
    head = [
        f"// brainsort {version()} - single-header distribution.",
        "// Generated by scripts/amalgamate.py from include/brainsort/; do not edit.",
        "// Copy this file into your project and #include \"brainsort.hpp\".",
        "// License: MIT, see LICENSE in the repository.",
        "#pragma once",
        "",
    ]
    return "\n".join(head + out).rstrip("\n") + "\n"


def main(argv):
    text = amalgamate()
    if "--check" in argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{OUT.relative_to(ROOT)} is out of date: run python3 scripts/amalgamate.py", file=sys.stderr)
            return 1
        print(f"{OUT.relative_to(ROOT)} is current")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
