[package]
name = "brainsort-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
brainsort = { path = "..", version = "0.3.0" }

[[bin]]
name = "sort"
path = "fuzz_targets/sort.rs"
test = false
doc = false
bench = false

[profile.release]
debug = 1
